version: '3'

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - 3001:3000
  #   stdin_open: true

  api:
    container_name: api
    build:
      context: backend/
      dockerfile: Dockerfile.api
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    container_name: database
    build:
      context: database/
      dockerfile: Dockerfile.db
